Add required option for function and assertions
0keeper1/nanotest pull request #11
Opened 2024-08-21 08:15 UTC by kehiy

2024-08-21 11:56 UTC, 0keeper1 requested changes

2024-08-21 11:56 UTC, 0keeper1 commented on src/lib.h
> +				fprintf( stderr, "Test %s is required and must pass to continue.\n", TESTNAME );       \
it's better to add a \tab before the line, like the one in the fprintf above ...

2024-08-21 11:56 UTC, 0keeper1 commented on src/lib.h
> +				fprintf( stderr, "Test %s is required and must pass to continue.\n", TESTNAME );       \
But this line is not required ... you can handle It with one input in the print above ...

2024-08-21 11:56 UTC, 0keeper1 commented on src/lib.h
> +		if ( required )                                                                                        \
This condition just causes panic and doesn't need to be checked if the Assert passed.

```c
		if ( expected > actual )                                                                               \
		{                                                                                                      \
			TOTAL_FAILED_COUNTER++;                                                                        \
			TOTAL_FAILED_COUNTER_PER_FUNCTION++;                                                           \
			fprintf( stderr, "- \t\"%s\" %s:%d Error: expected %d to be greater than %d.\n", TESTNAME,     \
				 __FILE__, __LINE__, expected, actual );                                               \
			if ( required )                                                                                        \
		        {                                                                                                      \
			      fprintf( stderr, "Test %s is required and must pass to continue.\n", TESTNAME );               \
			      exit( 1 );                                                                                     \
		         }                                                                                                      \
		}                                                                                                      \
		else                                                                                                   \
		{                                                                                                      \
			TOTAL_SUCCESSFUL_COUNTER++;                                                                    \
			TOTAL_SUCCESSFUL_COUNTER_PER_FUNCTION++;                                                       \
			fprintf( stderr, "+ \t\"%s\" %s:%d Ok.\n", TESTNAME, __FILE__, __LINE__ );                     \
		}                                                                                                      \
```

2024-08-21 12:43 UTC, 0keeper1 requested changes

2024-08-21 12:43 UTC, 0keeper1 commented on src/lib.h
> +#define NANO_ASSERT_EQ_INT( TESTNAME, expected, actual, required )                                                     \
set required as optional input:
`__VA_OPT__`

https://en.cppreference.com/w/cpp/preprocessor/replace

2024-08-24 13:02 UTC, kehiy commented on src/lib.h
> +#define NANO_ASSERT_EQ_INT( TESTNAME, expected, actual, required )                                                     \
I'm facing with an strange warning:

```
__VA_OPT__ can only appear in the expansion of a variadic macro.
```

2024-08-30 08:53 UTC, 0keeper1 commented on src/lib.h
> +			assert( required == false );                                                                   \
Assert is not required here use `exit(1);` instead.

2024-08-30 10:04 UTC, kehiy commented on src/lib.h
> +			assert( required == false );                                                                   \
We must exit only when requierd is set to true! not always!

2024-09-02 19:26 UTC, merged